#!/usr/bin/env bash
# Auto-rename tmux windows running Claude Code or Codex CLI.
#
# Target format: "cc/<title>" for Claude, "cdx/<title>" for Codex, or
# "cc/<linear-id>/<title>" / "cdx/<linear-id>/<title>" when a Linear issue
# (AMILABS-<n>) is mentioned anywhere in the session. <title> is a 3-6 word
# summary of the session's overall scope — how it started plus where it
# currently stands — generated by an LLM (default: openai/gpt-5.4-nano via
# OpenRouter). Cached per session, keyed to the source transcript's mtime —
# reused untouched while the session is idle, regenerated the next time it's
# rescanned after new content lands.
#
# Usage:
#   agent-rename.sh              # scan all windows
#   agent-rename.sh --current    # scan only the current window (fast, for hooks)
#   agent-rename.sh --clear      # clear title cache

set -euo pipefail

CLAUDE_SESSIONS="${HOME}/.claude/sessions"
CLAUDE_PROJECTS="${HOME}/.claude/projects"
CODEX_SESSIONS="${HOME}/.codex/sessions"
CACHE_DIR="${HOME}/.cache/tmux-ai-rename"
FALLBACK_MAX=14

mkdir -p "$CACHE_DIR"

# ── config from tmux options ────────────────────────────────

tmux_opt() {
  tmux show-option -gqv "$1" 2>/dev/null || true
}

RENAME_MODEL=$(tmux_opt '@autoname_model')
: "${RENAME_MODEL:=openai/gpt-5.4-nano}"

API_KEY="${OPENROUTER_API_KEY:-$(tmux_opt '@autoname_api_key')}"
if [[ -z "$API_KEY" ]]; then
  key_file="${OPENROUTER_API_KEY_FILE:-$HOME/.claude/credentials/openrouter-api-key}"
  [[ -s "$key_file" ]] && API_KEY="$(<"$key_file")"
fi

# Portable mtime (GNU stat on Linux, BSD stat on macOS).
file_mtime() {
  stat -c %Y "$1" 2>/dev/null || stat -f %m "$1" 2>/dev/null
}

# First AMILABS-<n> issue id mentioned anywhere in a session file (bare
# number only — the team is always AMILABS, so the prefix is redundant in a
# short window name). Empty if none found.
linear_issue_id() {
  local file="$1"
  [[ -f "$file" ]] || return 0
  grep -oE 'AMILABS-[0-9]+' "$file" 2>/dev/null | head -1 | grep -oE '[0-9]+' || true
}

# ── process tree snapshot ──────────────────────────────────
#
# `ps -axo comm=` returns the full executable path (possibly containing
# spaces — e.g. Claude.app's path lives under "Application Support").
# We keep only pid/ppid/comm here; argv is fetched per-pid on demand to
# avoid tokenisation pain.

PS_TREE=$(ps -axo pid=,ppid=,comm= 2>/dev/null || true)

# Print newline-separated descendant pids of $1 (excluding $1 itself).
descendants() {
  local root="$1"
  awk -v root="$root" '
    { parent[$1] = $2 }
    END {
      seen[root] = 1
      changed = 1
      while (changed) {
        changed = 0
        for (p in parent) {
          if (!seen[p] && seen[parent[p]]) { seen[p] = 1; changed = 1 }
        }
      }
      # NB: awk auto-creates empty entries in `seen` whenever
      # `seen[parent[p]]` is *read*, so we must filter on the value
      # (== 1) and not just on key membership.
      for (p in seen) if (seen[p] && p != root) print p
    }
  ' <<< "$PS_TREE"
}

# basename of a pid's `comm`, empty if not found. Handles comms that
# contain spaces (full paths under /Applications/, /Library/, etc.).
comm_base_of() {
  local pid="$1"
  awk -v pid="$pid" '
    $1 == pid {
      full = ""
      for (i = 3; i <= NF; i++) full = (full == "" ? $i : full " " $i)
      n = split(full, parts, "/")
      print parts[n]
      exit
    }
  ' <<< "$PS_TREE"
}

# Full argv for a pid.
pid_args_of() {
  ps -p "$1" -o args= 2>/dev/null || true
}

# Match an interactive agent. want = "claude" | "codex".
# Excludes MCP servers, Codex app-server, and the Claude Desktop helper
# (which runs with --output-format stream-json, i.e. not a TTY agent).
is_interactive_agent() {
  local pid="$1" want="$2"
  local base args
  base=$(comm_base_of "$pid") || return 1
  [[ "$base" == "$want" ]] || return 1
  args=$(pid_args_of "$pid")
  case "$args" in
    *' mcp-server'*|*' app-server'*|*' --output-format stream-json'*) return 1 ;;
  esac
  return 0
}

# Walk a pane's process subtree; print "type pid" for the first interactive
# claude/codex found. BFS-ish via awk closure, so shallowest match wins.
find_pane_agent() {
  local pane_pid="$1"
  # Check the pane_pid itself first (covers shells that exec claude directly).
  if is_interactive_agent "$pane_pid" "claude"; then printf 'claude %s\n' "$pane_pid"; return 0; fi
  if is_interactive_agent "$pane_pid" "codex";  then printf 'codex %s\n'  "$pane_pid"; return 0; fi
  while read -r kid; do
    [[ -n "$kid" ]] || continue
    if is_interactive_agent "$kid" "claude"; then printf 'claude %s\n' "$kid"; return 0; fi
    if is_interactive_agent "$kid" "codex";  then printf 'codex %s\n'  "$kid"; return 0; fi
  done < <(descendants "$pane_pid")
  return 1
}

# ── Claude session reading ──────────────────────────────────

claude_session_file() { printf '%s/%s.json\n' "$CLAUDE_SESSIONS" "$1"; }

claude_session_id() {
  local f
  f=$(claude_session_file "$1")
  [[ -f "$f" ]] || return 1
  jq -r '.sessionId' "$f" 2>/dev/null
}

claude_jsonl_path() {
  local claude_pid="$1" f session_id cwd project_dir jsonl
  f=$(claude_session_file "$claude_pid")
  [[ -f "$f" ]] || return 1
  session_id=$(jq -r '.sessionId' "$f" 2>/dev/null) || return 1
  cwd=$(jq -r '.cwd' "$f" 2>/dev/null) || return 1

  project_dir=$(echo "$cwd" | tr '/.' '--')
  jsonl="${CLAUDE_PROJECTS}/${project_dir}/${session_id}.jsonl"
  if [[ ! -f "$jsonl" ]]; then
    jsonl=$(find "$CLAUDE_PROJECTS" -name "${session_id}.jsonl" 2>/dev/null | head -1)
    [[ -n "$jsonl" ]] || return 1
  fi
  printf '%s\n' "$jsonl"
}

# Overall-scope content: the transcript's first user prompt (what it set out
# to do) plus its most recent user/assistant text (where it stands now) — so
# the title tracks the whole arc instead of drifting to just the latest line.
claude_scope_content() {
  local jsonl="$1"
  [[ -f "$jsonl" ]] || return 1
  python3 - "$jsonl" <<'PY' 2>/dev/null
import json, sys

def extract_text(entry):
    content = entry.get('message', {}).get('content', '')
    if isinstance(content, list):
        for item in content:
            if isinstance(item, dict) and item.get('type') == 'text' and item.get('text', '').strip():
                return item['text'].strip()
        return ''
    if isinstance(content, str):
        return content.strip()
    return ''

with open(sys.argv[1]) as f:
    lines = f.readlines()

first_text = ''
for line in lines:
    try: entry = json.loads(line)
    except Exception: continue
    if entry.get('type') != 'user': continue
    t = extract_text(entry)
    if t:
        first_text = t
        break

last_text = ''
for line in reversed(lines):
    try: entry = json.loads(line)
    except Exception: continue
    if entry.get('type') not in ('user', 'assistant'): continue
    t = extract_text(entry)
    if t:
        last_text = t
        break

parts = []
if first_text: parts.append('Started: ' + first_text[:250])
if last_text and last_text != first_text: parts.append('Latest: ' + last_text[:250])
combined = '\n'.join(parts)
if combined:
    print(combined[:600]); sys.exit(0)
sys.exit(1)
PY
}

# ── Codex session reading ──────────────────────────────────
#
# Codex stores each conversation in ~/.codex/sessions/YYYY/MM/DD/
# rollout-<ts>-<uuid>.jsonl. The running codex process keeps that file
# open for writing, so `lsof -p <pid>` reveals it deterministically —
# no cwd-guessing required.

codex_rollout_of() {
  local pid="$1"
  lsof -p "$pid" 2>/dev/null | awk '/rollout-.*\.jsonl/ { print $NF; exit }'
}

codex_session_id_of_rollout() {
  # rollout-YYYY-MM-DDTHH-MM-SS-<uuid>.jsonl  →  <uuid>
  local path="$1" base
  base="${path##*/}"
  base="${base%.jsonl}"
  base="${base#rollout-}"
  # Timestamp prefix is fixed-width: "YYYY-MM-DDTHH-MM-SS-" = 20 chars.
  printf '%s\n' "${base:20}"
}

# Overall-scope content: the rollout's first real user prompt (skipping
# Codex's auto-injected preamble turns) plus its most recent user/assistant
# text — so the title tracks the whole arc instead of just the latest line.
# Assistant turns carry their text under content type "output_text"; user
# turns under "input_text"/"text".
codex_scope_content() {
  local rollout="$1"
  [[ -f "$rollout" ]] || return 1
  python3 - "$rollout" <<'PY' 2>/dev/null
import json, sys

def extract_text(payload):
    content = payload.get('content')
    if isinstance(content, list):
        for c in content:
            if isinstance(c, dict) and c.get('type') in ('input_text', 'text', 'output_text'):
                t = (c.get('text') or '').strip()
                if t: return t
        return ''
    if isinstance(content, str):
        return content.strip()
    return ''

lines = open(sys.argv[1]).readlines()

first_text = ''
for line in lines:
    try: e = json.loads(line)
    except Exception: continue
    if e.get('type') != 'response_item': continue
    p = e.get('payload', {})
    if p.get('role') != 'user': continue
    t = extract_text(p)
    if not t: continue
    if t.startswith(('<environment_context>', '<user_instructions>', '# AGENTS.md')):
        continue
    first_text = t
    break

last_text = ''
for line in reversed(lines):
    try: e = json.loads(line)
    except Exception: continue
    if e.get('type') != 'response_item': continue
    p = e.get('payload', {})
    if p.get('role') not in ('user', 'assistant'): continue
    t = extract_text(p)
    if t:
        last_text = t
        break

parts = []
if first_text: parts.append('Started: ' + first_text[:250])
if last_text and last_text != first_text: parts.append('Latest: ' + last_text[:250])
combined = '\n'.join(parts)
if combined:
    print(combined[:600]); sys.exit(0)
sys.exit(1)
PY
}

# ── LLM summarisation ──────────────────────────────────────

summarise_prompt() {
  local raw="$1"
  [[ -n "$raw" ]] || return 1

  if [[ -z "$API_KEY" ]]; then
    printf '%s\n' "${raw:0:$FALLBACK_MAX}"
    return 0
  fi

  local escaped
  escaped=$(printf '%s' "$raw" \
    | python3 -c "import sys,json; print(json.dumps(sys.stdin.read().strip()))")

  local response
  response=$(curl -s --max-time 15 https://openrouter.ai/api/v1/chat/completions \
    -H "Authorization: Bearer $API_KEY" \
    -H "Content-Type: application/json" \
    -d "{
      \"model\": \"$RENAME_MODEL\",
      \"max_tokens\": 300,
      \"temperature\": 0,
      \"reasoning\": {\"effort\": \"low\"},
      \"messages\": [
        {\"role\": \"system\", \"content\": \"Generate a 3-6 word English window title capturing the OVERALL SCOPE of this task — weigh both how it started and where it currently stands, don't just describe the latest line. Rules: always English regardless of input language, include key nouns and action, no quotes, no punctuation, max 35 characters.\"},
        {\"role\": \"user\", \"content\": $escaped}
      ]
    }" 2>/dev/null) || true

  local title
  title=$(echo "$response" | jq -r '.choices[0].message.content // empty' 2>/dev/null)

  if [[ -n "$title" ]]; then
    printf '%s\n' "$title"
  else
    printf '%s\n' "${raw:0:$FALLBACK_MAX}"
  fi
}

# ── per-agent title pipelines (with cache) ─────────────────

# Returns "<linear_id>\t<title>" (linear_id may be empty). Both are cached
# in sibling files keyed to the same mtime gate, so a cache hit costs no
# LLM call and no re-grep.
claude_title() {
  local pid="$1" session_id jsonl cache mtime_file linear_file cur_mtime raw title linear_id
  session_id=$(claude_session_id "$pid") || return 1
  jsonl=$(claude_jsonl_path "$pid") || return 1
  cur_mtime=$(file_mtime "$jsonl") || return 1
  cache="${CACHE_DIR}/claude-${session_id}"
  mtime_file="${cache}.mtime"
  linear_file="${cache}.linear"
  if [[ -s "$cache" && "$(cat "$mtime_file" 2>/dev/null)" == "$cur_mtime" ]]; then
    printf '%s\t%s\n' "$(cat "$linear_file" 2>/dev/null || true)" "$(cat "$cache")"
    return 0
  fi
  raw=$(claude_scope_content "$jsonl") || return 1
  [[ -n "$raw" ]] || return 1
  title=$(summarise_prompt "$raw")
  linear_id=$(linear_issue_id "$jsonl")
  printf '%s\n' "$title" > "$cache"
  printf '%s\n' "$cur_mtime" > "$mtime_file"
  printf '%s\n' "$linear_id" > "$linear_file"
  printf '%s\t%s\n' "$linear_id" "$title"
}

codex_title() {
  local pid="$1" rollout session_id cache mtime_file linear_file cur_mtime raw title linear_id
  rollout=$(codex_rollout_of "$pid")
  [[ -n "$rollout" ]] || return 1
  session_id=$(codex_session_id_of_rollout "$rollout")
  [[ -n "$session_id" ]] || return 1
  cur_mtime=$(file_mtime "$rollout") || return 1
  cache="${CACHE_DIR}/codex-${session_id}"
  mtime_file="${cache}.mtime"
  linear_file="${cache}.linear"
  if [[ -s "$cache" && "$(cat "$mtime_file" 2>/dev/null)" == "$cur_mtime" ]]; then
    printf '%s\t%s\n' "$(cat "$linear_file" 2>/dev/null || true)" "$(cat "$cache")"
    return 0
  fi
  raw=$(codex_scope_content "$rollout") || return 1
  [[ -n "$raw" ]] || return 1
  title=$(summarise_prompt "$raw")
  linear_id=$(linear_issue_id "$rollout")
  printf '%s\n' "$title" > "$cache"
  printf '%s\n' "$cur_mtime" > "$mtime_file"
  printf '%s\n' "$linear_id" > "$linear_file"
  printf '%s\t%s\n' "$linear_id" "$title"
}

# ── window labelling ────────────────────────────────────────

label_window() {
  local window_id="$1" prefix="$2" desc="$3" ai_pid="$4" linear_id="${5:-}"
  local name="$desc"
  if [[ -n "$prefix" && -n "$linear_id" ]]; then
    name="${prefix}/${linear_id}/${desc}"
  elif [[ -n "$prefix" ]]; then
    name="${prefix}/${desc}"
  fi

  # Idempotent, but placeholder-aware: skip only when this window is already
  # labelled for the same agent AND already shows the desired name. Keying the
  # skip on the final name (not just @ai_pid) lets a placeholder "cc/?" upgrade
  # to the real title once the first prompt is persisted — the pid is unchanged
  # but the name now differs, so we relabel instead of staying frozen.
  local current_pid current_name
  current_pid=$(tmux show-options -wv -t "$window_id" @ai_pid 2>/dev/null || true)
  current_name=$(tmux display-message -p -t "$window_id" '#{window_name}' 2>/dev/null || true)
  if [[ "$current_pid" == "$ai_pid" && "$current_name" == "$name" ]]; then
    return 0
  fi

  tmux set-option -w -t "$window_id" automatic-rename off 2>/dev/null || true
  tmux set-option -w -t "$window_id" @ai_pid "$ai_pid" 2>/dev/null || true
  tmux rename-window -t "$window_id" "$name" 2>/dev/null || true
}

unlabel_window() {
  local window_id="$1"
  local was_ai
  was_ai=$(tmux show-options -wv -t "$window_id" @ai_pid 2>/dev/null || true)
  [[ -n "$was_ai" ]] || return 0
  tmux set-option -wu -t "$window_id" @ai_pid 2>/dev/null || true
  tmux set-option -w -t "$window_id" automatic-rename on 2>/dev/null || true
}

# ── main ────────────────────────────────────────────────────

if [[ "${1:-}" == "--clear" ]]; then
  rm -rf "${CACHE_DIR:?}/"*
  echo "Title cache cleared."
  exit 0
fi

# Background refresh loop: re-scan every N seconds so titles resolve and stay
# fresh without needing a window/pane switch (tmux has no timer hook). The loop
# self-terminates when the tmux server exits.
#
# Single-instance is COOPERATIVE, not kill-based. An earlier version killed the
# previous watcher on every reload — that surfaced as "terminated by signal 15"
# noise and, under two near-simultaneous reloads, raced (each read the old pid
# before the other wrote) and stacked watchers. Instead every watcher claims the
# pidfile by writing its own PID (last writer wins) and checks ownership each
# tick, exiting cleanly the moment a newer watcher has taken over. No signals,
# no stacking — concurrent spawns converge to exactly one within a tick.
if [[ "${1:-}" == "--watch" ]]; then
  interval="${2:-30}"
  [[ "$interval" =~ ^[0-9]+$ && "$interval" -gt 0 ]] || interval=30
  pidfile="${CACHE_DIR}/watch.pid"
  printf '%s\n' "$$" > "$pidfile"
  # Exit cleanly (status 0) on TERM/INT so an external kill never shows up as a
  # signal in tmux's run-shell log.
  trap 'exit 0' TERM INT
  # Only reclaim the pidfile if we still own it, so a superseded watcher's exit
  # never deletes the live watcher's entry.
  trap '[[ "$(cat "$pidfile" 2>/dev/null)" == "$$" ]] && rm -f "$pidfile"' EXIT
  # --current keeps this cheap: it only walks the active window's pane tree,
  # which is the case the periodic refresh exists for (a brand-new session's
  # "cc/?" upgrading once its first prompt lands while you sit in that window).
  # Background windows still resolve on their own switch hooks; prefix + R does
  # a full sweep on demand.
  while tmux has-session 2>/dev/null; do
    [[ "$(cat "$pidfile" 2>/dev/null)" == "$$" ]] || exit 0   # a newer watcher took over
    bash "$0" --current >/dev/null 2>&1 || true
    sleep "$interval"
  done
  exit 0
fi

if [[ "${1:-}" == "--current" ]]; then
  pane_list=$(tmux list-panes -F '#{pane_pid} #{window_id}' 2>/dev/null)
  window_list=$(tmux display-message -p '#{window_id}')
else
  pane_list=$(tmux list-panes -a -F '#{pane_pid} #{window_id}' 2>/dev/null)
  window_list=$(tmux list-windows -a -F '#{window_id}' 2>/dev/null)
fi

process_window() {
  local target_wid="$1"
  local ai_type="" ai_pid=""

  while read -r pane_pid wid; do
    [[ "$wid" == "$target_wid" ]] || continue
    local found
    found=$(find_pane_agent "$pane_pid" || true)
    [[ -n "$found" ]] || continue
    ai_type=${found%% *}
    ai_pid=${found##* }
    break
  done <<< "$pane_list"

  if [[ -n "$ai_pid" ]]; then
    local title prefix combined linear_id
    if [[ "$ai_type" == "claude" ]]; then
      prefix="cc"
      combined=$(claude_title "$ai_pid" 2>/dev/null || true)
    else
      prefix="cdx"
      combined=$(codex_title "$ai_pid" 2>/dev/null || true)
    fi
    # combined is "<linear_id>\t<title>"; a failed lookup leaves it empty,
    # which parameter expansion below just turns into an empty title too.
    linear_id="${combined%%$'\t'*}"
    title="${combined#*$'\t'}"
    [[ -n "$title" ]] || title="?"
    label_window "$target_wid" "$prefix" "$title" "$ai_pid" "$linear_id"
  else
    unlabel_window "$target_wid"
  fi
}

while read -r wid; do
  [[ -n "$wid" ]] || continue
  process_window "$wid"
done <<< "$window_list"
